LAYERLIB =\
layerlib/AuxLemma.v \
layerlib/MemoryExtra.v \
layerlib/LAsm.v \
layerlib/LAsmModuleSemDef.v \
layerlib/LAsmModuleSemAux.v \
layerlib/AsmImplLemma.v \
layerlib/PrimSemantics.v \
layerlib/XOmega.v \
layerlib/ASTExtra.v \
layerlib/AuxStateDataType.v \
layerlib/Behavior.v \
layerlib/ObservationImpl.v \
layerlib/CommonTactic.v \
layerlib/Constant.v \
layerlib/RefinementTactic.v \
layerlib/GlobIdent.v \
layerlib/LAsmgen.v \
layerlib/LAsmgenproof.v \
layerlib/LRegSet.v \
layerlib/LayerCalculusLemma.v \
layerlib/mCertiKOSType.v \
layerlib/AsmImplTactic.v \
layerlib/LAsmModuleSemSim.v \
layerlib/LAsmModuleSemMakeProgram.v \
layerlib/LAsmModuleSemAsmInv.v \
layerlib/LAsmModuleSemHighInv.v \
layerlib/LAsmModuleSemLowInv.v \
layerlib/LAsmModuleSemProp.v \
layerlib/LAsmModuleSemMonotonic.v \
layerlib/LAsmModuleSem.v \
layerlib/LAsmModuleSemSpec.v \
layerlib/LAsmModuleSemInvariants.v \
layerlib/LAsmModuleSemEvent.v \
layerlib/LAsmModuleSemTransfer.v \
layerlib/LinkTactic.v \
layerlib/Soundness.v \
layerlib/CompCertiKOS.v \
layerlib/CompCertiKOSproof.v \
layerlib/CompCertiKOSproofImpl.v \
layerlib/LinkSourceTemplate.v \
layerlib/LinkTemplate.v \
layerlib/Z64Lemma.v \

INVLEMMA =\
invariants/INVLemmaContainer.v \
invariants/INVLemmaMemory.v \
invariants/INVLemmaThread.v \
invariants/INVLemmaProc.v \
#invariants/INVLemmaIntel.v \


FLATMEM=\
flatmem/LoadStoreDef.v \
flatmem/PageFault.v \
flatmem/LoadStoreGeneral.v \
flatmem/FlatLoadStoreSem.v \
flatmem/HostAccess0.v \
flatmem/GuestAccessIntelDef0.v \
flatmem/GuestAccessIntelRef0.v \
flatmem/GuestAccessIntel0.v \
flatmem/HostAccess1.v \
flatmem/GuestAccessIntel1.v \
flatmem/HostAccess2.v \
flatmem/GuestAccessIntelDef2.v \
flatmem/GuestAccessIntel2.v \
flatmem/LoadStoreSem0.v \
flatmem/LoadStoreSem1.v \
flatmem/LoadStoreSem2.v \
flatmem/LoadStoreSem3.v \
flatmem/FlatMemory.v \
#flatmem/GuestAccessAmd0.v \
#flatmem/GuestAccessAmd1.v \
flatmem/LoadStoreSemAmd0.v \


CLIB=\
clib/CLemmas.v \
clib/TacticsForTesting.v \
clib/CalRealPTPool.v \
clib/CalRealPT.v \
clib/CDataTypes.v \
clib/RealParams.v \
clib/LoopProof.v \
clib/VCGen.v \
clib/CalRealIDPDE.v \
clib/CalRealInitPTE.v \
clib/CalRealSMSPool.v \
clib/CalRealProcModule.v \

#clib/CalRealVirtModule.v 
#clib/CInitSpecsvirt.v 
#clib/CInitSpecsproc.v 
#clib/CalRealFreePT.v 


OBJECTS=\
objects/AbstractDataType.v \
objects/ObjCPU.v \
objects/ObjMM.v \
objects/ObjFlatMem.v \
objects/ObjPMM.v \
objects/ObjVMMDef.v \
objects/ObjVMMGetSet.v \
objects/ObjVMMFun.v \
objects/ObjVMM.v \
objects/ObjLMM0.v \
objects/ObjLMM1.v \
objects/ObjLMM.v \
objects/ObjShareMem.v \
objects/ObjThread.v \
objects/ObjQueue.v \
objects/ObjProc.v \
objects/ObjArg.v \
objects/ObjTrap.v \
objects/ObjContainer.v \
objects/ObjSyncIPC.v \
#objects/ObjEPT.v \
objects/ObjVMCS.v \
objects/ObjVMX.v \


MM=\
mm/MMDataType.v \
mm/MBoot.v \
mm/MBootCSource.v \
mm/MBootCode.v \
mm/MContainer.v \
mm/ContainerGenSpec.v \
mm/ContainerGen.v \
mm/ContainerGenLinkSource.v \
mm/ContainerGenLink.v \
mm/MALInit.v \
mm/ALInitGenSpec.v \
mm/ALInitGenDef.v \
mm/ALInitGenFresh.v \
mm/ALInitGenPassthrough.v \
mm/ALInitGen.v \
mm/ALInitGenLinkSource.v \
mm/ALInitGenLink.v \
mm/MALOp.v \
mm/ALOpGenSpec.v \
mm/ALOpGen.v \
mm/ALOpGenLinkSource.v \
mm/ALOpGenLink.v \
mm/MALT.v \
mm/ALGenSpec.v \
mm/ALGen.v \
mm/ALGenLinkSource.v \
mm/ALGenLink.v \
mm/MPTIntro.v \
mm/PTIntroGenSpec.v \
mm/PTIntroGenDef.v \
mm/PTIntroGenFresh.v \
mm/PTIntroGenPassthrough.v \
mm/PTIntroGenAccessorDef.v \
mm/PTIntroGenAccessor0.v \
mm/PTIntroGenAccessor.v \
mm/PTIntroGenPassthrough.v \
mm/PTIntroGen.v \
mm/PTIntroGenAsm.v \
mm/PTIntroGenLinkSource.v \
mm/PTIntroGenLink.v \
mm/MPTOp.v \
mm/PTOpGenSpec.v \
mm/PTOpGen.v \
mm/PTOpGenLinkSource.v \
mm/PTOpGenLink.v \
mm/MPTCommon.v \
mm/PTCommGenSpec.v \
mm/PTCommGen.v \
mm/PTCommGenLinkSource.v \
mm/PTCommGenLink.v \
mm/MPTKern.v \
mm/PTKernGenSpec.v \
mm/PTKernGen.v \
mm/PTKernGenLinkSource.v \
mm/PTKernGenLink.v \
mm/MPTInit.v \
mm/PTInitGen.v \
mm/PTInitGenSpec.v \
mm/PTInitGenLinkSource.v \
mm/PTInitGenLink.v \
mm/MPTNew.v \
mm/PTNewGenSpec.v \
mm/PTNewGen.v \
mm/PTNewGenLinkSource.v \
mm/PTNewGenLink.v \
mm/MShareIntro.v \
mm/ShareIntroGenSpec.v \
mm/ShareIntroGenDef.v \
mm/ShareIntroGenPassthrough.v \
mm/ShareIntroGenFresh.v \
mm/ShareIntroGen.v \
mm/ShareIntroGenLinkSource.v \
mm/ShareIntroGenLink.v \
mm/MShareOp.v \
mm/ShareOpGen.v \
mm/ShareOpGenSpec.v \
mm/ShareOpGenLinkSource.v \
mm/ShareOpGenLink.v \
mm/MShare.v \
mm/ShareGen.v \
mm/ShareGenSpec.v \
mm/ShareGenLinkSource.v \
mm/ShareGenLink.v \
mm/MALTCSource.v \
mm/MPTIntroCSource.v \
mm/MPTOpCSource.v \
mm/MPTCommonCSource.v \
mm/MPTKernCSource.v \
mm/MPTInitCSource.v \
mm/MPTNewCSource.v \
mm/MShareOpCSource.v \
mm/MShareIntroCSource.v \
mm/MALInitCSource.v \
mm/MALOpCSource.v \
mm/MContainerCSource.v \
mm/MALInitCode.v \
mm/MALOpCode.v \
mm/MALTCode.v \
mm/MPTInitCode.v \
mm/MPTIntroCode.v \
mm/MPTKernCode.v \
mm/MPTCommonCode.v \
mm/MPTOpCode.v \
mm/PTIntroGenAsmSource.v \
mm/MPTNewCode.v \
mm/MShareOpCode.v \
mm/MShareIntroCode.v \
mm/MShareIntroCodeSharedMemInit.v \
mm/MContainerCode.v \
#mm/PreInit.v \
mm/PreInitCSource.v \
mm/PreInitCode.v \
mm/BootGenSpec.v \
mm/BootGenDef.v \
mm/BootGenLemma.v \
mm/BootGenAccessorDef.v \
mm/BootGenAccessor0.v \
mm/BootGenAccessor.v \
mm/BootGenFresh.v \
mm/BootGenPassthrough.v \
mm/BootGen.v \
mm/BootGenLinkSource.v \
mm/BootGenLink.v \


PROC=\
proc/MShareCSource.v \
proc/MShareCode.v \
proc/PKContext.v \
proc/KContextGenSpec.v \
proc/KContextGen.v \
proc/KContextGenAsm.v \
proc/KContextGenLinkSource.v \
proc/KContextGenLink.v \
proc/PKContextNew.v \
proc/KContextNewGenSpec.v \
proc/KContextNewGen.v \
proc/KContextNewGenLinkSource.v \
proc/KContextNewGenLink.v \
proc/PThreadIntro.v \
proc/PThreadIntroCSource.v \
proc/PThreadIntroCode.v \
proc/ThreadIntroGenSpec.v \
proc/ThreadIntroGenDef.v \
proc/ThreadIntroGenFresh.v \
proc/ThreadIntroGenPassthrough.v \
proc/ThreadIntroGen.v \
proc/ThreadIntroGenLinkSource.v \
proc/ThreadIntroGenLink.v \
proc/PThreadInit.v \
proc/ThreadInitGenSpec.v \
proc/ThreadInitGen.v \
proc/ThreadInitGenLinkSource.v \
proc/ThreadInitGenLink.v \
proc/PQueueIntro.v \
proc/PQueueIntroCode.v \
proc/PQueueIntroCSource.v \
proc/QueueIntroGenSpec.v \
proc/QueueIntroGenDef.v \
proc/QueueIntroGenFresh.v \
proc/QueueIntroGenPassthrough.v \
proc/QueueIntroGen.v \
proc/QueueIntroGenLinkSource.v \
proc/QueueIntroGenLink.v \
proc/PQueueInit.v \
proc/QueueInitGenSpec.v \
proc/QueueInitGen.v \
proc/QueueInitGenLinkSource.v \
proc/QueueInitGenLink.v \
proc/PAbQueue.v \
proc/AbQueueGen.v \
proc/PAbQueueCSource.v \
proc/PAbQueueCode.v \
proc/AbQueueGenLink.v \
proc/PCurID.v \
proc/PCurIDCSource.v \
proc/PCurIDCode.v \
proc/CurIDGenSpec.v \
proc/CurIDGen.v \
proc/CurIDGenLinkSource.v \
proc/CurIDGenLink.v \
proc/PThreadSched.v \
proc/ThreadSchedGenSpec.v \
proc/ThreadSchedGen.v \
proc/ThreadSchedGenAsmData.v \
proc/ThreadSchedGenAsm.v \
proc/ThreadSchedGenLinkSource.v \
proc/ThreadSchedGenLink.v \
proc/PThread.v \
proc/PThreadCSource.v \
proc/PThreadCode.v \
proc/ThreadGenSpec.v \
proc/ThreadGen.v \
proc/ThreadGenAsmData.v \
proc/ThreadGenAsm1.v \
proc/ThreadGenAsm.v \
proc/ThreadGenLinkSource.v \
proc/ThreadGenLink.v \
proc/PIPCIntro.v \
proc/PIPCIntroCSource.v \
proc/PIPCIntroCode.v \
proc/IPCIntroGenSpec.v \
proc/IPCIntroGenDef.v \
proc/IPCIntroGenFresh.v \
proc/IPCIntroGenPassthrough.v \
proc/IPCIntroGen.v \
proc/IPCIntroGenLinkSource.v \
proc/IPCIntroGenLink.v \
proc/PIPC.v \
proc/PIPCCode.v \
proc/PIPCCSource.v \
proc/IPCGenSpec.v \
proc/IPCGen.v \
proc/IPCGenLinkSource.v \
proc/IPCGenLink.v \
proc/PUCtxtIntroDef.v \
proc/PUCtxtIntro.v \
proc/PUCtxtIntroCSource.v \
proc/PUCtxtIntroCode.v \
proc/UCtxtIntroGenSpec.v \
proc/UCtxtIntroGenDef.v \
proc/UCtxtIntroGenFresh0.v \
proc/UCtxtIntroGenFresh.v \
proc/UCtxtIntroGenPassthrough.v \
proc/UCtxtIntroGen.v \
proc/UCtxtIntroGenAsm.v \
proc/UCtxtIntroGenLinkSource.v \
proc/UCtxtIntroGenLink.v \
proc/PProc.v \
proc/ProcGenSpec.v \
proc/ProcGen.v \
proc/ProcGenAsmData.v \
proc/ProcGenAsm.v \
proc/ProcGenAsm1.v \
proc/PKContextCSource.v \
proc/PKContextCode.v \
proc/PKContextNewCSource.v \
proc/PKContextNewCode.v \
proc/PThreadInitCSource.v \
proc/PThreadInitCode.v \
proc/KContextGenAsmSource.v \
proc/ThreadSchedGenAsmSource.v \
proc/ThreadGenAsmSource.v \
proc/UCtxtIntroGenAsmSource.v \
proc/ProcGenAsmSource.v \
proc/ProcGenLinkSource.v \
proc/ProcGenLink.v \


INTELVIRT=\
virt/intel/IntelPrimSemantics.v \
virt/intel/PProcCSource.v \
virt/intel/PProcCode.v \
virt/intel/EPTIntroGenSpec.v \
virt/intel/EPTIntroGenDef.v \
virt/intel/EPTIntroGenAccessor.v \
virt/intel/EPTIntroGenPassthrough.v \
virt/intel/EPTIntroGenFresh.v \
virt/intel/EPTIntroGen.v \
virt/intel/EPTIntroGenLinkSource.v \
virt/intel/EPTIntroGenLink.v \
virt/intel/VEPTIntro.v \
virt/intel/VEPTIntroCSource.v \
virt/intel/VEPTIntroCode.v \
virt/intel/VEPTIntroCodeEPTInit.v \
virt/intel/EPTOpGenSpec.v \
virt/intel/EPTOpGen.v \
virt/intel/EPTOpGenAsmSource.v \
virt/intel/EPTOpGenAsm.v \
virt/intel/EPTOpGenLinkSource.v \
virt/intel/EPTOpGenLink.v \
virt/intel/VEPTOp.v \
virt/intel/VEPTOpCSource.v \
virt/intel/VEPTOpCode.v \
virt/intel/EPTInitGenSpec.v \
virt/intel/EPTInitGen.v \
virt/intel/EPTInitGenLinkSource.v \
virt/intel/EPTInitGenLink.v \
virt/intel/VEPTInitCSource.v \
virt/intel/VEPTInitCode.v \
virt/intel/VEPTInit.v \
virt/intel/VMCSIntroGenSpec.v \
virt/intel/VMCSIntroGenDef.v \
virt/intel/VMCSIntroGenPassthrough.v \
virt/intel/VMCSIntroGenFresh.v \
virt/intel/VMCSIntroGen.v \
virt/intel/VMCSIntroGenAsmSource.v \
virt/intel/VMCSIntroGenAsm.v \
virt/intel/VMCSIntroGenAsm1.v \
virt/intel/VMCSIntroGenLinkSource.v \
virt/intel/VMCSIntroGenLink.v \
virt/intel/VVMCSIntro.v \
virt/intel/VVMCSIntroCSource.v \
virt/intel/VVMCSIntroCode.v \
virt/intel/VVMCSIntroCodeSetDesc.v \
virt/intel/VVMCSIntroCodeSetDefaults.v \
virt/intel/VMCSInitGen.v \
virt/intel/VMCSInitGenSpec.v \
virt/intel/VMCSInitGenLinkSource.v \
virt/intel/VMCSInitGenLink.v \
virt/intel/VVMCSInit.v \
virt/intel/VVMCSInitCSource.v \
virt/intel/VVMCSInitCode.v \
virt/intel/VMXIntroGenSpec.v \
virt/intel/VMXIntroGenDef.v \
virt/intel/VMXIntroGenPassthrough.v \
virt/intel/VMXIntroGenFresh.v \
virt/intel/VMXIntroGen.v \
virt/intel/VMXIntroGenAsmSource.v \
virt/intel/VMXIntroGenAsm.v \
virt/intel/VMXIntroGenLinkSource.v \
virt/intel/VVMXIntro.v \
virt/intel/VVMXIntroCSource.v \
virt/intel/VVMXIntroCode.v \
virt/intel/VMXIntroGenLinkSource.v \
virt/intel/VMXIntroGenLink.v \
virt/intel/VMXInitGen.v \
virt/intel/VMXInitGenSpec.v \
virt/intel/VMXInitGenAsmSource.v \
virt/intel/VMXInitGenAsmData.v \
virt/intel/VMXInitGenAsm.v \
virt/intel/VMXInitGenLinkSource.v \
virt/intel/VMXInitGenLink.v \
virt/intel/VVMXInit.v \
#virt/VNPTIntro.v 
#virt/NPTIntroGenSpec.v 
#virt/NPTIntroGen.v 


TRAP=\
trap/TrapPrimSemantics.v \
trap/PProcCSource.v \
trap/PProcCode.v \
trap/TrapArgGenSpec.v \
trap/TrapArgGen.v \
trap/TTrapArg.v \
trap/TTrapArgCSource.v \
trap/TTrapArgCode.v \
trap/TTrapArgCode2.v \
trap/TrapArgGenLinkSource.v \
trap/TrapArgGenLink.v \
trap/TrapGenSpec.v \
trap/TrapGen.v \
trap/TrapGenLinkSource.v \
trap/TrapGenLink.v \
trap/TTrap.v \
trap/TTrapCSource.v \
trap/TTrapCode.v \
trap/DispatchGenSpec.v \
trap/DispatchGen.v \
trap/DispatchGenLinkSource.v \
trap/DispatchGenLink.v \
trap/TDispatch.v \
trap/SysCallGenSpec.v \
trap/SysCallGen.v \
trap/SysCallGenAsmSource.v \
trap/SysCallGenAsmData.v \
trap/SysCallGenAsm.v \
trap/SysCallGenAsm2.v \
trap/SysCallGenLinkSource.v \
trap/SysCallGenLink.v \
trap/TSysCall.v \


SECURITY=\
security/SecurityCommon.v \
security/ObsEq.v \
security/SecurityInv1.v \
security/SecurityInv2.v \
security/SecurityInv.v \
security/SecurityExtra.v \
security/Integrity.v \
security/Confidentiality.v \
security/ConfidentialityRestore.v \
security/SafeSecure.v \
security/SecurityBigstep.v \
security/Security.v \
policy/ExamplePolicies.v \

DRIVER=\
driver/Symbols.v \
driver/CertiKOSImpl.v \
driver/RealParamsImpl.v \
driver/CertiKOS.v \
driver/CertiKOSAux.v \
driver/CertiKOSproof.v \


FILES=\
$(LAYERLIB) \
$(CLIB) \
$(FLATMEM) \
$(OBJECTS) \
$(INVLEMMA) \
$(MM) \
$(PROC) \
$(TRAP) \
$(VIRT) \
$(DRIVER) \
$(SECURITY) \


# Options used with ocamlbuild for the extracted code
OCB_OPTIONS=\
  -no-hygiene -no-links -j 2 \
  -I mcertikos/extraction \
  -I mcertikos/driver \
  -I compcert/lib \
  -I compcert/common \
  -I compcert/ia32/standard \
  -I compcert/ia32 \
  -I compcert/backend \
  -I compcert/cfrontend \
  -I compcert/flocq/Core \
  -I compcert/flocq/Prop \
  -I compcert/flocq/Calc \
  -I compcert/flocq/Appli \
  -I compcert/driver \
  -I compcert/cparser \


# In addition to compiling all of the proofs in $(FILES),
# we want to build the ccertikos binary
all: ccertikos

# Include the common rules and targets as well
include ../subdir.mk

# Ruby may not be available, in which case we just touch the old version of
# these files. This is also why we don't remove them in the 'clean' target.
layerlib/GlobIdent.v: script/ident_config script/mCertiKOS.rb
	cd script && ruby mCertiKOS.rb ident || true
driver/Symbols.v: script/ident_config script/mCertiKOS.rb
	cd script && ruby mCertiKOS.rb symbols || true

# Extract ML code
extraction/CertiKOS.ml: driver/CertiKOS.vo
	$(COQTOP) -batch -load-vernac-source ./extraction/extraction.v

# Build the extracted code
ccertikos: extraction/CertiKOS.ml driver/PrintLAsm.ml ../compcert/driver/Configuration.ml
	cd .. && \
	$(OCAMLBUILD) $(OCB_OPTIONS) CertiKOSDriver.native && \
	mv _build/mcertikos/driver/CertiKOSDriver.native mcertikos/ccertikos

# Add the related cleanup commands
clean: clean-extraction
clean-extraction:
	$(RM) extraction/*.ml* certikos.s ccertikos
